### ISSUE TITLE
Enhance README to summarize results

### ISSUE THREAD

**Issue by gwaybio** [WayScience/NF1_SchwannCell_data_analysis#62]
@MattsonCam and I are chatting now on our 1on1. @jenna-tomkinson, would you be able to enhance the README a bit? I imagine this would be:

1.  Add a couple sentence summary of our overall finding
2. Add a couple main figures with legends
3. Describe future steps

**Comment by MattsonCam** [comment]
@jenna-tomkinson can we close this issue, since #65 was merged?

**Comment by jenna-tomkinson** [comment]
Yup this issue can be closed with #65 being merged!
