### ISSUE TITLE
Update/fix gitmodule

### ISSUE THREAD

**Issue by gwaybio** [WayScience/NF1_SchwannCell_data_analysis#63]
The submodule is currently 404 (see [link](https://github.com/WayScience/NF1_SchwannCell_data_analysis/blob/main/nf1_painting_repo))

I think this is because the `.gitmodules` file is currently empty as of 3d27dd643b21516057596745b19dc06d36c0c9d1

**Comment by MattsonCam** [comment]
Since #66 has been merged, I will close this issue.
