### ISSUE TITLE
Mint DOI

### ISSUE THREAD

**Issue by gwaybio** [WayScience/NF1_SchwannCell_data_analysis#64]
As a last step, we need to mint a DOI for the repo. Steps here: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

## Greg TODO

- Click `on` for this repo

## Cameron TODO

- Generate version 1 release

**Comment by gwaybio** [comment]
@MattsonCam should generate release:

# after merging 

- [x] #60 
- [x] #61 
- [x] #68 
- [x] #69
- [x] Add README pr(s)

and addressing 

- [x] #62
- [x] #63

**Comment by jenna-tomkinson** [comment]
I have a few more PRs to do for supplemental figures after main figure 4. @gwaybio @MattsonCam Should we wait to release once the repo has all supplemental figures as well? I don't see this on the to-do list.

**Comment by gwaybio** [comment]
Yep, we totally should wait. Can you add specifics to the bullet points?

(We should also have a similar running list for the data repo)

**Comment by jenna-tomkinson** [comment]
> Yep, we totally should wait. Can you add specifics to the bullet points? (We should also have a similar running list for the data repo)
> […](#)

Awesome! I have added a temporary bullet point for the supplemental figures. Will update with each PR as I make them. I need to finalize them, but it should be about 3-4 supplemental figures.

**Comment by jenna-tomkinson** [comment]
@MattsonCam and @gwaybio All supplemental figures have been created, so please feel free to perform any more software gardening if necessary! Minting can happen unless more is needed :smile:

**Comment by gwaybio** [comment]
If you've completed all checklist, then mint away!

**Comment by jenna-tomkinson** [comment]
@gwaybio Actually Cameron and I agreed to add a README for the figures module so I will submit and merge that PR and THEN we are good to mint!

**Comment by jenna-tomkinson** [comment]
@MattsonCam Feel free to mint when you feel it is ready! All cleared up with PR #70.

**Comment by MattsonCam** [comment]
Just created [Release 1](https://github.com/WayScience/NF1_SchwannCell_data_analysis/releases/tag/v1.0)! I think Zenodo is also archiving the repo after following [these steps](https://github.com/WayScience/NF1_SchwannCell_data_analysis/issues/64#issue-2451704663). Can somebody verify that the minting is completed for this repo before closing this issue?
